// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5IadkGOuxglju8EgTSYb8GDoBnoEC7IY',
    appId: '1:806737479808:web:f6a6a894d8ae9ef94ebe65',
    messagingSenderId: '806737479808',
    projectId: 'aura-1999',
    authDomain: 'aura-1999.firebaseapp.com',
    databaseURL: 'https://aura-1999-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'aura-1999.appspot.com',
    measurementId: 'G-F5GVYMQ9XE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPX_DOhkvKIVCqnnswVzkULOuCSurzC6o',
    appId: '1:806737479808:android:668bad2d391a92374ebe65',
    messagingSenderId: '806737479808',
    projectId: 'aura-1999',
    databaseURL: 'https://aura-1999-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'aura-1999.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCRBa2c2xaCUK7F8Ph-yaF8EqT8cLg2NzU',
    appId: '1:806737479808:ios:8a1bcee12369c4fc4ebe65',
    messagingSenderId: '806737479808',
    projectId: 'aura-1999',
    databaseURL: 'https://aura-1999-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'aura-1999.appspot.com',
    iosBundleId: 'com.example.aurahome',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCRBa2c2xaCUK7F8Ph-yaF8EqT8cLg2NzU',
    appId: '1:806737479808:ios:f75b4a2a7888bb4e4ebe65',
    messagingSenderId: '806737479808',
    projectId: 'aura-1999',
    databaseURL: 'https://aura-1999-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'aura-1999.appspot.com',
    iosBundleId: 'com.example.aurahome.RunnerTests',
  );
}
